config/routes.rb
Rails.application.routes.draw do
  resources :appointments, only: [:new, :create]
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :time_slot
	validates :book_date, presence: true, future_date_only: true, uniqueness: {scope: :time_slot_id}
	def start_time
        self.book_date
    end

    def name
    	"#{self.time_slot.start_time.strftime('%H:%M %p')} - #{self.time_slot.end_time.strftime('%H:%M %p')}"
    end
end

app/models/concerns/future_date_only_validator.rb
class FutureDateOnlyValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
	    if value.present? && value < Date.today
	      record.errors.add attribute,
	                        (options[:message] || "can't be in the past")
	    end
  	end
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
	has_many :appointments, dependent: :delete_all

	def slot_name
		"#{self.start_time.strftime('%H:%M %p')} - #{self.end_time.strftime('%H:%M %p')}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index

    @appointments = Appointment.all
    
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new(book_date: params[:book_date])
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to root_path(start_date: @appointment.book_date), notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to root_path(start_date: @appointment.book_date), notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:note, :book_date, :time_slot_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	start_date = Date.current
	start_date = DateTime.parse(params['start_date']).try(:to_date) if params['start_date'].present?
  	@appointments = Appointment.includes(:time_slot).where(book_date: start_date.beginning_of_month..start_date.end_of_month)
  	# @avaible_slots = Appointment.group(:book_date).pluck("book_date, CASE WHEN count(*) = (select count(*) from time_slots) THEN false ELSE true END").to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
	   case level
	   when :notice then "alert alert-info"
	   when :success then "alert alert-success"
	   when :error then "alert alert-danger"
	   when :alert then "alert alert-danger"
	   end
    end
    
	# Check for current month day only
	def current_month_day date
		start_date = current_date = Date.current
		start_date = DateTime.parse(params['start_date']).try(:to_date) if params['start_date'].present?
		start_date = start_date.beginning_of_month
		end_date = start_date.end_of_month
		return true if date >= current_date && date >= start_date && date <= end_date
		false
	end

	def all_slots_count
		@all_slots_count ||= TimeSlot.count
	end

	def time_slots_options book_date=nil
		return [] if book_date.nil?
		TimeSlot.where.not(id: Appointment.where(book_date: book_date).pluck(:time_slot_id)).collect{|t| [t.slot_name, t.id]}
	end

	def is_available? sorted_events, day
		return true unless sorted_events.fetch(day, []).count == all_slots_count
		false
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.association :time_slot, collection: time_slots_options(f.object.book_date), prompt: "Select time slot", required: true %>
    <%= f.input :book_date %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Slot</th>
      <th>Book date</th>
      <th>Note</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.name %></td>
        <td><%= appointment.book_date %></td>
        <td><%= appointment.note %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Book date:</strong>
  <%= @appointment.book_date %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/home/index.html.erb
<div class="row">
	<%= month_calendar  events: @appointments do |date, appointments| %>
		
  		<span class="date-str"><%= date.day %></span>
  		<% appointments.each do |appointment| %>
		    <div>
		      <%= appointment.name %>
		    </div>
	   <% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlotBooking</title>
    <meta http-equiv="Expires" content="30" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'screen,projection' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<div class="container">
      <%= render 'shared/header' %>
      <%= render 'shared/messages' %>
  		<%= yield %>
      <div class="row"><hr></div>
      <%= render 'shared/footer' %>
  	</div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div>
    <p class="text-muted">slot-booking@2017</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="row">
	<div class="col-md-12"><h1 class="text-center">Slot booking</h1></div>
</div>
<div class="row"><hr></div>

app/views/shared/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
	<% unless flash[level].blank? %>
		<div class="<%= flash_class(level) %> alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
			<%= flash[level].html_safe %> 
		</div>     
	<% end %>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center text-large">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day), data: {date: day} do %>
              <% block.call day, sorted_events.fetch(day, []) %>
              <div class="book-now-btn">
                <%= link_to "book now", new_appointment_path(book_date: day), class: 'btn btn-sm' if current_month_day(day) && is_available?(sorted_events, day) %>
              </div>
              
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>